#!/bin/bash
###
#
# @Author	  lanthean
# @Created	  29/11/2021
# 
###

echo "--- Removing compiled inc"
rm inc
rm ~/bin/inc
echo "--- Removing bash completion script"
if [[ $(uname) == "Darwin" ]];then
    rm /opt/homebrew/etc/bash_completion.d/inc
    rm /opt/homebrew/etc/bash_completion.d/ops
else
    sudo rm /etc/bash_completion.d/inc
    sudo rm /etc/bash_completion.d/ops
fi
echo "--- clean done"

#EOF
###