#!/bin/bash
###
#
# @Author	  lanthean
# @Created	  29/11/2021
# 
###

echo "--- compiling inc.sh"
shc -f inc.sh -o inc
if [ $? != 0 ];then
  echo "[ERROR] compile failed"
  exit 1
fi

echo "--- create/Update ~/bin/inc link"
ln -sf ${PWD}/inc ~/bin/inc
sudo ln -sf ${PWD}/bash_completion.d/inc /etc/bash_completion.d/
sudo ln -sf ${PWD}/bash_completion.d/ops /etc/bash_completion.d/
echo "--- compile done"

#EOF
###
