#!/bin/bash
###
#
# @Author	  lanthean
# @Created	  29/11/2021
# 
###

echo "--- Compiling inc.sh"
shc -f inc.sh -o inc

echo "--- Create/Update ~/bin/inc link"
ln -sf ${PWD}/inc ~/bin/inc

if [[ $(uname) == "Darwin" ]];then
    ln -sf ${PWD}/bash_completion.d/inc /opt/homebrew/etc/bash_completion.d/
    ln -sf ${PWD}/bash_completion.d/ops /opt/homebrew/etc/bash_completion.d/
else
    sudo ln -sf ${PWD}/bash_completion.d/inc /etc/bash_completion.d/
    sudo ln -sf ${PWD}/bash_completion.d/ops /etc/bash_completion.d/
fi
echo "--- compile done"
echo "--- source bash_completion"
if [[ $(uname) == "Darwin" ]];then
    source /opt/homebrew/etc/bash_completion.d/inc
    source /opt/homebrew/etc/bash_completion.d/ops
else
    source /etc/bash_completion.d/inc
    source /etc/bash_completion.d/ops
fi
echo "--- source bash_completion done"

#EOF
###