#!/bin/bash
###
#
# @Author	  lanthean
# @Created	  29/11/2021
# 
###

echo "--- Installing prerequisites"
if [ $(uname) == "Darwin" ];then
    brew install shc

elif [ $(uname -v) == *"Ubuntu"* ];then
    sudo apt install shc
else
    sudo yum -y install shc
fi
echo "--- pre done"

#EOF
###
